### ISSUE TITLE
For the love of god i am unable to display it in Home assistant as Horizantal

### ISSUE THREAD

**Issue by MikeONLCH** [FamousWolf/week-planner-card#17]
Trying to build this i managed to get the Calendar setup but everytime the days of the week are vertically 1 above the other is there a sample code you have availible to achive the horizantal view as display in the example card

type: custom:week-planner-card
days: 7
noCardBackground: true
eventBackground: rgba(0, 0, 0, 0.1)
updateInterval: 60
calendars:
  - entity: calendar.gezin
    color: '#e6c229'
texts:
  noEvents: Geen activiteiten
  fullDay: Hele dag
  today: Vandaag
  tomorrow: Morgen
  sunday: Zondag
  monday: Maandag
  tuesday: Dinsdag
  wednesday: Woensdag
  thursday: Donderdag
  friday: Vrijdag
  saturday: Zaterdag

**Comment by FamousWolf** [comment]
@MikeONLCH This could be because you're placing the card on a masonry view (which is default). This view places cards in columns. Even if you only add 1 card. This means the card will only be as wide as the column. If you change the view type to panel or sidebar it should become wider. See https://www.home-assistant.io/dashboards/views/ for more about views.

If this isn't the problem, please provide more information like a screenshot.

**Comment by MikeONLCH** [comment]
Should I just immediately do the walk of shame?

views:
  - title: Your View Title
    path: your_path
    panel: true
    cards:
      - type: custom:week-planner-card
        days: 7
        noCardBackground: true
        eventBackground: rgba(0, 0, 0, 0.1)
        updateInterval: 60
        calendars:
          - entity: calendar.gezin
            color: '#e6c229'
        texts:
          noEvents: Geen activiteiten
          fullDay: Hele dag
          today: Vandaag
          tomorrow: Morgen
          sunday: Zondag
          monday: Maandag
          tuesday: Dinsdag
          wednesday: Woensdag
          thursday: Donderdag
          friday: Vrijdag
          saturday: Zaterdag
